### ISSUE TITLE
/bin/arm-none-eabi-g++ Error

### ISSUE THREAD

**Issue by Fusion-Lightguns** [SeongGino/ir-light-gun-plus#12]
Hello. So i also forked Prow7 and been working on simliar stuff. You have some features I dont so I wanted to try yours out. 

I installed all boards and what not, using a Pi Pico.
I select Pico fix as board and ttry and burn 2.1 hotfixes.

I recieve 
exec: "/bin/arm-none-eabi-g++": file does not exist

Compilation error: exec: "/bin/arm-none-eabi-g++": file does not exist

**Comment by SeongGino** [comment]
Are you running Linux? That sounds like missing GCC files - especially since it isn't pointing to a relative Arduino path. It's not something I can reproduce.

May want to make sure to follow the instruction manual included in the sketch directory.

**Comment by Fusion-Lightguns** [comment]
I am using windows and followed the instruction manual. 

Im running ide 2.1 normal install, imported all libraries and checked i was on right board. 
Not a big deal just wanted to try your code & figured you should know errors.

**Comment by SeongGino** [comment]
Then that sounds like an IDE issue. Do other sketches work?
I don't use Windows and I haven't heard this from other users (no idea how many of them use Win, but I have to assume they do), so. :woman_shrugging:

**Comment by SeongGino** [comment]
Since this seems to be an IDE problem separate from the sketch directly (and no response), I'll be closing this.

EDIT: retrospect in case this ever comes up again, we pull our build tools from Earle's core directly, which creates an adjacent `rp2040` directory where they're stored (because currently the manual instructs to use a fork rather than upstream, for #3). While this doesn't seem to affect Linux, it might be possible that this messes with Windows installs - in the meantime, copying the tools folder in `rp2040/` to `rp2040-tri/` might suffice? If this comes up again then that might be an issue with the core fork.

**Comment by Fusion-Lightguns** [comment]
Sorry holidays and life got me caught up for awhile. 

All other sketches worked . I tried my sketches, a blink and different examples. 

I can try
"the meantime, copying the tools folder in rp2040/ to rp2040-tri/ might suffice?"

In the next day or two.

**Comment by SeongGino** [comment]
Given that compilation has worked for other users as soon as a few days ago, it's strange that this problem seems to be effecting your environment.

Currently, manual building isn't the recommendation anymore, as prebuilt binaries are distributed now since v3.0, though having build errors is obviously still a concern.

Since editing my last comment, I've updated the core fork's index file so it should be using the `rpipico` directory like upstream--I believe you'll have to remove whatever older version of the core fork you had installed and reinstall the fixed core.

Do let me know if that's fixed it for you.
