### ISSUE TITLE
any possible to support BT wireless mode

### ISSUE THREAD

**Issue by hpx1984** [SeongGino/ir-light-gun-plus#27]
Hi Sir SeongGino

do you have plane to let this lightgun project to support BT wireless mode in future?

**Comment by SeongGino** [comment]
Hi! I appreciate the interest.

As you might have noticed, this project has since moved under the [OpenFIRE](https://github.com/TeamOpenFIRE) umbrella. As a result, there won't be any more activity in the old GUN4ALL repositories.

Appropriately, among one of the many updates done to that project over this is Bluetooth support, though it is still a work in progress.

Again, I appreciate the understanding.
